/**
 * Image Generation Nodes - AI image generation models
 */
import type { NodeDefinition } from '@/models/canvas';

export const imageGenNodes: NodeDefinition[] = [
  {
    type: 'flux2Pro',
    category: 'imageGen',
    label: 'FLUX.2 Pro',
    displayName: 'Photo Generator (Pro)',
    description: 'Create stunning, photorealistic images from text descriptions. Best for high-quality, commercial-ready output.',
    quickHelp: 'Connect a text prompt → Generate beautiful images',
    useCase: 'Product photos, fashion designs, concept art',
    icon: 'AutoAwesome',
    aiModel: 'flux-2-pro',
    tier: 'production',
    inputs: [
      { id: 'prompt', name: 'Prompt (Text Input)', type: 'text', required: true },
      { id: 'reference', name: 'Reference (Image Upload)', type: 'image' },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'guidance', name: 'Guidance Scale', type: 'slider', default: 3.5, min: 1, max: 20, step: 0.1 },
      { id: 'numImages', name: 'Num Images', type: 'number', default: 1, min: 1, max: 4 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'image', aspectRatio: '1:1', showZoom: true, showVariations: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['width', 'height', 'guidance'] },
      actions: { primary: 'execute', secondary: ['download', 'duplicate'], showProgress: true },
    },
  },
  {
    type: 'flux2Dev',
    category: 'imageGen',
    label: 'FLUX.2 Dev',
    displayName: 'Photo Generator (Dev)',
    description: 'Generate images with custom style training (LoRA) support. Great for personal styles.',
    quickHelp: 'Text prompt + optional style → Custom-styled images',
    useCase: 'Personal art styles, trained aesthetics, experimental looks',
    icon: 'Science',
    aiModel: 'flux-2-dev',
    tier: 'creative',
    inputs: [
      { id: 'prompt', name: 'Prompt (Text Input)', type: 'text', required: true },
      { id: 'style', name: 'Style (LoRA Training)', type: 'style' },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'steps', name: 'Steps', type: 'number', default: 28, min: 1, max: 50 },
      { id: 'guidance', name: 'Guidance Scale', type: 'slider', default: 3.5, min: 1, max: 20, step: 0.1 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'image', aspectRatio: '1:1', showZoom: true, showVariations: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['width', 'height', 'steps'] },
      actions: { primary: 'execute', secondary: ['download', 'duplicate'], showProgress: true },
    },
  },
  {
    type: 'nanoBananaPro',
    category: 'imageGen',
    label: 'Nano Banana Pro',
    displayName: 'Multi-Character Scene',
    description: 'Create images with multiple specific people using reference photos. Supports up to 5 different faces.',
    quickHelp: 'References + Prompt → Scene with those people',
    useCase: 'Group photos, family portraits, multi-character stories',
    icon: 'GroupAdd',
    aiModel: 'nano-banana-pro',
    tier: 'production',
    bestFor: 'faces',
    inputs: [
      { id: 'prompt', name: 'Prompt (Text Input)', type: 'text', required: true },
      { id: 'references', name: 'Face Photos (Image Upload)', type: 'image', multiple: true },
      { id: 'characters', name: 'Characters (Character Reference)', type: 'character', multiple: true },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'faceWeight', name: 'Face Weight', type: 'slider', default: 0.8, min: 0, max: 1, step: 0.1 },
      { id: 'styleWeight', name: 'Style Weight', type: 'slider', default: 0.6, min: 0, max: 1, step: 0.1 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'image', aspectRatio: '1:1', showZoom: true, showVariations: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['faceWeight', 'styleWeight'] },
      actions: { primary: 'execute', secondary: ['download', 'duplicate'], showProgress: true },
    },
  },
  {
    type: 'fluxKontext',
    category: 'imageGen',
    label: 'FLUX Kontext',
    displayName: 'Smart Image Editor',
    description: 'Make targeted edits to existing images using text instructions. Change outfits, backgrounds, or details.',
    quickHelp: 'Image + "Change X to Y" → Edited image',
    useCase: 'Outfit changes, background swaps, detail modifications',
    icon: 'Transform',
    aiModel: 'flux-kontext',
    tier: 'production',
    inputs: [
      { id: 'image', name: 'Source Image (Image Upload)', type: 'image', required: true },
      { id: 'prompt', name: 'Edit Prompt (Text Input)', type: 'text', required: true },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'strength', name: 'Edit Strength', type: 'slider', default: 0.8, min: 0, max: 1, step: 0.05 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'image', aspectRatio: 'auto', showZoom: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['strength'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
  // === NEW DECEMBER 2025 IMAGE MODELS ===
  {
    type: 'flux2Max',
    category: 'imageGen',
    label: 'FLUX.2 Max',
    displayName: 'Photo Generator (Flagship)',
    description: 'State-of-the-art image generation with exceptional realism and multi-reference synthesis (up to 10 images). Best quality available.',
    quickHelp: 'Prompt + up to 10 references → Highest quality images',
    useCase: 'Commercial photography, premium content, multi-reference scenes',
    icon: 'Stars',
    aiModel: 'flux-2-max',
    tier: 'flagship',
    cost: '$0.07/megapixel',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
      { id: 'references', name: 'References (up to 10)', type: 'image', multiple: true },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 4096 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 4096 },
      { id: 'guidance', name: 'Guidance Scale', type: 'slider', default: 3.5, min: 1, max: 20, step: 0.1 },
      { id: 'numImages', name: 'Num Images', type: 'number', default: 1, min: 1, max: 4 },
    ],
  },
  {
    type: 'recraftV3',
    category: 'imageGen',
    label: 'Recraft V3',
    displayName: 'Text & Brand Designer',
    description: 'Best-in-class for text rendering, vector art, and brand-style generation. Creates posters, ads, and designs with readable long-form text.',
    quickHelp: 'Perfect for posters, ads, logos, and branded content',
    useCase: 'Posters, advertisements, brand materials, vector graphics',
    icon: 'FormatShapes',
    aiModel: 'recraft-v3',
    tier: 'production',
    bestFor: 'text',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
      { id: 'brandStyle', name: 'Brand Style Reference', type: 'image', multiple: true },
    ],
    outputs: [
      { id: 'image', name: 'Raster Image', type: 'image' },
      { id: 'vector', name: 'Vector (SVG)', type: 'style' },
    ],
    parameters: [
      { id: 'style', name: 'Style', type: 'select', default: 'realistic', options: [
        { label: 'Realistic', value: 'realistic' },
        { label: 'Digital Illustration', value: 'digital_illustration' },
        { label: 'Vector Art', value: 'vector_illustration' },
        { label: 'Icon', value: 'icon' },
      ]},
      { id: 'textContent', name: 'Text to Include', type: 'text', default: '' },
      { id: 'brandColors', name: 'Brand Colors (hex)', type: 'text', default: '' },
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 2048 },
    ],
  },
  {
    type: 'gptImage',
    category: 'imageGen',
    label: 'GPT Image 1.5',
    displayName: 'GPT Image Generator',
    description: 'OpenAI multimodal image generation with strongest prompt adherence and understanding.',
    quickHelp: 'Most accurate prompt interpretation',
    useCase: 'Complex scenes, precise instructions, detailed compositions',
    icon: 'Psychology',
    aiModel: 'gpt-image-1.5',
    tier: 'flagship',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'numImages', name: 'Num Images', type: 'number', default: 1, min: 1, max: 4 },
    ],
  },
  {
    type: 'zImageTurbo',
    category: 'imageGen',
    label: 'Z-Image Turbo',
    displayName: 'Fast Image Generator',
    description: 'Ultra-fast 6B parameter model for quick iterations and rapid prototyping.',
    quickHelp: 'Fastest generation for quick previews',
    useCase: 'Rapid prototyping, quick iterations, concept exploration',
    icon: 'FlashOn',
    aiModel: 'flux-schnell',
    tier: 'fast',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
    ],
    outputs: [{ id: 'image', name: 'Image', type: 'image' }],
    parameters: [
      { id: 'width', name: 'Width', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'height', name: 'Height', type: 'number', default: 1024, min: 256, max: 2048 },
      { id: 'numImages', name: 'Num Images', type: 'number', default: 1, min: 1, max: 4 },
    ],
  },
];
