/**
 * Storytelling Nodes - Narrative, Character, World Building, Dialogue, Branching
 */
import type { NodeDefinition } from '@/models/canvas';

export const storytellingNodes: NodeDefinition[] = [
  // ============================================================================
  // NARRATIVE FOUNDATION
  // ============================================================================
  {
    type: 'storyGenesis',
    category: 'narrative',
    label: 'Story Genesis',
    displayName: 'Create Story Concept',
    description: 'Transform a simple idea into a complete story concept with theme, premise, characters, and structure.',
    quickHelp: 'Idea → Full story concept with characters, conflict, and resolution',
    useCase: 'Starting a new story from scratch, brainstorming sessions',
    icon: 'AutoStories',
    inputs: [
      { id: 'idea', name: 'Core Idea', type: 'text', required: true },
      { id: 'genreHints', name: 'Genre Hints', type: 'text' },
      { id: 'toneStyle', name: 'Tone/Style', type: 'style' },
    ],
    outputs: [
      { id: 'story', name: 'Story Concept', type: 'story' },
      { id: 'characters', name: 'Character Seeds', type: 'character', multiple: true },
      { id: 'outline', name: 'Basic Outline', type: 'outline' },
      { id: 'locations', name: 'Location Seeds', type: 'location', multiple: true },
    ],
    parameters: [
      { id: 'genre', name: 'Primary Genre', type: 'select', default: 'drama', options: [
        { label: 'Drama', value: 'drama' },
        { label: 'Comedy', value: 'comedy' },
        { label: 'Thriller/Mystery', value: 'thriller' },
        { label: 'Romance', value: 'romance' },
        { label: 'Science Fiction', value: 'scifi' },
        { label: 'Fantasy', value: 'fantasy' },
        { label: 'Horror', value: 'horror' },
        { label: 'Action/Adventure', value: 'action' },
        { label: 'Historical', value: 'historical' },
        { label: "Children's", value: 'childrens' },
      ]},
      { id: 'length', name: 'Target Length', type: 'select', default: 'short', options: [
        { label: 'Flash Fiction (< 1,000 words)', value: 'flash' },
        { label: 'Short Story (1,000-7,500)', value: 'short' },
        { label: 'Novelette (7,500-20,000)', value: 'novelette' },
        { label: 'Novella (20,000-50,000)', value: 'novella' },
        { label: 'Novel (50,000+)', value: 'novel' },
        { label: 'Script (90-120 pages)', value: 'script' },
      ]},
      { id: 'audience', name: 'Target Audience', type: 'select', default: 'general', options: [
        { label: 'Children (5-12)', value: 'children' },
        { label: 'Young Adult', value: 'ya' },
        { label: 'General Adult', value: 'general' },
        { label: 'Mature', value: 'mature' },
      ]},
      { id: 'complexity', name: 'Narrative Complexity', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'storyStructure',
    category: 'narrative',
    label: 'Story Structure',
    displayName: 'Apply Story Framework',
    description: 'Structure your story using proven frameworks like Save the Cat, Hero\'s Journey, or Three-Act Structure.',
    quickHelp: 'Story concept → Structured beat sheet with all major plot points',
    useCase: 'Organizing a story, ensuring proper pacing and structure',
    icon: 'AccountTree',
    inputs: [
      { id: 'story', name: 'Story Concept', type: 'story', required: true },
      { id: 'characters', name: 'Main Characters', type: 'character', multiple: true },
    ],
    outputs: [
      { id: 'outline', name: 'Structured Outline', type: 'outline' },
      { id: 'beats', name: 'Story Beats', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'framework', name: 'Structure Framework', type: 'select', default: 'saveTheCat', options: [
        { label: 'Save the Cat (15 Beats)', value: 'saveTheCat' },
        { label: "Hero's Journey (12 Stages)", value: 'herosJourney' },
        { label: 'Three-Act Structure', value: 'threeAct' },
        { label: 'Five-Act Structure', value: 'fiveAct' },
        { label: 'Story Circle (Dan Harmon)', value: 'storyCircle' },
        { label: 'Freytag\'s Pyramid', value: 'freytag' },
        { label: 'Seven-Point Story Structure', value: 'sevenPoint' },
        { label: 'Fichtean Curve', value: 'fichtean' },
        { label: 'In Medias Res', value: 'inMediasRes' },
        { label: 'Kishotenketsu (4-Act)', value: 'kishotenketsu' },
      ]},
      { id: 'detailLevel', name: 'Beat Detail Level', type: 'select', default: 'standard', options: [
        { label: 'High-Level (Major beats only)', value: 'minimal' },
        { label: 'Standard (All framework beats)', value: 'standard' },
        { label: 'Detailed (Sub-beats included)', value: 'detailed' },
        { label: 'Comprehensive (Scene-level)', value: 'comprehensive' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'treatmentGenerator',
    category: 'narrative',
    label: 'Treatment Generator',
    displayName: 'Write Treatment',
    description: 'Generate a professional story treatment, synopsis, or logline from your story materials.',
    quickHelp: 'Story + Outline → Professional treatment document',
    useCase: 'Pitching to producers, query letters, story documentation',
    icon: 'Description',
    inputs: [
      { id: 'story', name: 'Story Concept', type: 'story', required: true },
      { id: 'outline', name: 'Story Outline', type: 'outline' },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
    ],
    outputs: [
      { id: 'treatment', name: 'Treatment Document', type: 'treatment' },
      { id: 'logline', name: 'Logline', type: 'text' },
      { id: 'synopsis', name: 'Synopsis', type: 'text' },
    ],
    parameters: [
      { id: 'format', name: 'Treatment Format', type: 'select', default: 'film', options: [
        { label: 'Film Treatment (2-5 pages)', value: 'film' },
        { label: 'TV Series Bible', value: 'tvBible' },
        { label: 'Novel Synopsis', value: 'novelSynopsis' },
        { label: 'Short Story Pitch', value: 'shortPitch' },
        { label: 'Game Narrative Doc', value: 'gameNarrative' },
      ]},
      { id: 'tone', name: 'Writing Tone', type: 'select', default: 'professional', options: [
        { label: 'Professional/Industry', value: 'professional' },
        { label: 'Enthusiastic/Pitch', value: 'enthusiastic' },
        { label: 'Literary/Artistic', value: 'literary' },
      ]},
      { id: 'includeLogline', name: 'Include Logline', type: 'boolean', default: true },
      { id: 'includeSynopsis', name: 'Include Synopsis', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'sceneGenerator',
    category: 'narrative',
    label: 'Scene Generator',
    displayName: 'Write Scene',
    description: 'Generate a complete scene with action, dialogue, and atmospheric description.',
    quickHelp: 'Scene concept → Fully written scene with all elements',
    useCase: 'Writing individual scenes, filling in outline gaps',
    icon: 'Theaters',
    inputs: [
      { id: 'sceneConcept', name: 'Scene Concept', type: 'text' },
      { id: 'plotPoint', name: 'Story Beat', type: 'plotPoint' },
      { id: 'outline', name: 'Story Outline', type: 'outline' },
      { id: 'characters', name: 'Characters in Scene', type: 'character', multiple: true },
      { id: 'location', name: 'Location', type: 'location' },
      { id: 'precedingScene', name: 'Previous Scene', type: 'scene' },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'scene', name: 'Complete Scene', type: 'scene' },
      { id: 'dialogue', name: 'Extracted Dialogue', type: 'dialogue' },
      { id: 'storyboardPrompts', name: 'Visual Prompts', type: 'text', multiple: true },
    ],
    parameters: [
      { id: 'format', name: 'Output Format', type: 'select', default: 'prose', options: [
        { label: 'Prose/Novel', value: 'prose' },
        { label: 'Screenplay', value: 'screenplay' },
        { label: 'Stage Play', value: 'stageplay' },
        { label: 'Graphic Novel Script', value: 'comicScript' },
      ]},
      { id: 'pov', name: 'Point of View', type: 'select', default: 'third-limited', options: [
        { label: 'First Person', value: 'first' },
        { label: 'Third Person Limited', value: 'third-limited' },
        { label: 'Third Person Omniscient', value: 'third-omniscient' },
        { label: 'Second Person', value: 'second' },
      ]},
      { id: 'sceneType', name: 'Scene Type', type: 'select', default: 'dramatic', options: [
        { label: 'Action/Chase', value: 'action' },
        { label: 'Dramatic Confrontation', value: 'dramatic' },
        { label: 'Romantic', value: 'romantic' },
        { label: 'Comedic', value: 'comedic' },
        { label: 'Suspense/Tension', value: 'suspense' },
        { label: 'Quiet/Reflective', value: 'quiet' },
        { label: 'Expository', value: 'expository' },
      ]},
      { id: 'length', name: 'Target Length', type: 'select', default: 'medium', options: [
        { label: 'Short (500-1000 words)', value: 'short' },
        { label: 'Medium (1000-2000 words)', value: 'medium' },
        { label: 'Long (2000-4000 words)', value: 'long' },
      ]},
      { id: 'generateVisualPrompts', name: 'Generate Visual Prompts', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'plotPoint',
    category: 'narrative',
    label: 'Plot Point',
    displayName: 'Create Plot Point',
    description: 'Define a key story beat - an event, revelation, or turning point.',
    quickHelp: 'Concept → Structured plot beat with cause/effect',
    useCase: 'Building plot progressions, defining key moments',
    icon: 'TrendingUp',
    inputs: [
      { id: 'concept', name: 'Event Concept', type: 'text', required: true },
      { id: 'precedingPlot', name: 'Previous Plot Point', type: 'plotPoint' },
      { id: 'characters', name: 'Characters Involved', type: 'character', multiple: true },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'plotPoint', name: 'Plot Point', type: 'plotPoint' },
      { id: 'consequences', name: 'Consequences', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'beatType', name: 'Beat Type', type: 'select', default: 'turning-point', options: [
        { label: 'Inciting Incident', value: 'inciting' },
        { label: 'Complication', value: 'complication' },
        { label: 'Turning Point', value: 'turning-point' },
        { label: 'Revelation', value: 'revelation' },
        { label: 'Confrontation', value: 'confrontation' },
        { label: 'Crisis', value: 'crisis' },
        { label: 'Climax', value: 'climax' },
        { label: 'Resolution', value: 'resolution' },
        { label: 'Cliffhanger', value: 'cliffhanger' },
      ]},
      { id: 'stakes', name: 'Stakes Level', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
      { id: 'emotionalImpact', name: 'Emotional Impact', type: 'select', default: 'mixed', options: [
        { label: 'Positive/Triumphant', value: 'positive' },
        { label: 'Negative/Devastating', value: 'negative' },
        { label: 'Mixed/Bittersweet', value: 'mixed' },
        { label: 'Neutral/Informational', value: 'neutral' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'plotTwist',
    category: 'narrative',
    label: 'Plot Twist',
    displayName: 'Create Twist',
    description: 'Generate a surprising plot twist that recontextualizes the story.',
    quickHelp: 'Story → Unexpected twist with proper foreshadowing',
    useCase: 'Adding surprises, raising stakes, subverting expectations',
    icon: 'Shuffle',
    inputs: [
      { id: 'story', name: 'Story So Far', type: 'story', required: true },
      { id: 'outline', name: 'Story Outline', type: 'outline' },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
    ],
    outputs: [
      { id: 'twist', name: 'Plot Twist', type: 'plotPoint' },
      { id: 'foreshadowing', name: 'Foreshadowing Hints', type: 'text', multiple: true },
      { id: 'aftermath', name: 'Aftermath Implications', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'twistType', name: 'Twist Type', type: 'select', default: 'revelation', options: [
        { label: 'Hidden Identity Reveal', value: 'identity' },
        { label: 'Betrayal', value: 'betrayal' },
        { label: 'False Memory/Reality', value: 'reality' },
        { label: 'Unexpected Ally/Enemy', value: 'allegiance' },
        { label: 'Time-Related', value: 'temporal' },
        { label: 'Hidden Connection', value: 'connection' },
        { label: 'Genre Subversion', value: 'genre' },
        { label: 'The Real Villain', value: 'villain' },
        { label: 'Sacrifice/Cost', value: 'sacrifice' },
      ]},
      { id: 'intensity', name: 'Twist Intensity', type: 'slider', default: 0.7, min: 0, max: 1, step: 0.1 },
      { id: 'includeForeshadowing', name: 'Include Foreshadowing', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'conflictGenerator',
    category: 'narrative',
    label: 'Conflict Generator',
    displayName: 'Create Conflict',
    description: 'Generate internal or external conflicts that drive your story forward.',
    quickHelp: 'Characters + Story → Compelling obstacles and challenges',
    useCase: 'Adding tension, creating obstacles, driving character growth',
    icon: 'Bolt',
    inputs: [
      { id: 'story', name: 'Story Context', type: 'story' },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
      { id: 'location', name: 'Setting', type: 'location' },
    ],
    outputs: [
      { id: 'conflict', name: 'Conflict', type: 'plotPoint' },
      { id: 'escalations', name: 'Escalation Steps', type: 'plotPoint', multiple: true },
      { id: 'resolution', name: 'Possible Resolutions', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'conflictType', name: 'Conflict Type', type: 'select', default: 'interpersonal', options: [
        { label: 'Person vs. Person', value: 'interpersonal' },
        { label: 'Person vs. Self (Internal)', value: 'internal' },
        { label: 'Person vs. Nature', value: 'nature' },
        { label: 'Person vs. Society', value: 'society' },
        { label: 'Person vs. Technology', value: 'technology' },
        { label: 'Person vs. Supernatural', value: 'supernatural' },
        { label: 'Person vs. Fate/Time', value: 'fate' },
      ]},
      { id: 'intensity', name: 'Conflict Intensity', type: 'slider', default: 0.6, min: 0, max: 1, step: 0.1 },
      { id: 'includeEscalation', name: 'Include Escalation Path', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'storyPivot',
    category: 'narrative',
    label: 'Story Pivot',
    displayName: 'Pivot Story',
    description: 'Radically change your story\'s direction while maintaining coherence.',
    quickHelp: 'Story + New direction → Transformed narrative',
    useCase: 'Major rewrites, genre shifts, exploring alternatives',
    icon: 'SwapHoriz',
    inputs: [
      { id: 'story', name: 'Current Story', type: 'story', required: true },
      { id: 'newDirection', name: 'New Direction', type: 'text', required: true },
    ],
    outputs: [
      { id: 'pivotedStory', name: 'Pivoted Story', type: 'story' },
      { id: 'newOutline', name: 'New Outline', type: 'outline' },
      { id: 'characterUpdates', name: 'Character Changes', type: 'character', multiple: true },
    ],
    parameters: [
      { id: 'pivotType', name: 'Pivot Type', type: 'select', default: 'direction', options: [
        { label: 'Direction Change', value: 'direction' },
        { label: 'Genre Shift', value: 'genre' },
        { label: 'Tone Transformation', value: 'tone' },
        { label: 'Protagonist Switch', value: 'protagonist' },
        { label: 'Timeline Shift', value: 'timeline' },
        { label: 'Scale Change (Bigger/Smaller)', value: 'scale' },
      ]},
      { id: 'preserveRatio', name: 'Preservation Level', type: 'slider', default: 0.4, min: 0, max: 1, step: 0.1 },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'intrigueLift',
    category: 'narrative',
    label: 'Intrigue Lift',
    displayName: 'Add Intrigue',
    description: 'Inject mystery, tension, and unanswered questions into your story.',
    quickHelp: 'Story → Enhanced with secrets, mysteries, and tension',
    useCase: 'Making stories more compelling, adding mystery layers',
    icon: 'VisibilityOff',
    inputs: [
      { id: 'story', name: 'Current Story', type: 'story', required: true },
      { id: 'outline', name: 'Story Outline', type: 'outline' },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
    ],
    outputs: [
      { id: 'secrets', name: 'Hidden Secrets', type: 'plotPoint', multiple: true },
      { id: 'mysteries', name: 'Story Mysteries', type: 'plotPoint', multiple: true },
      { id: 'tensionPoints', name: 'Tension Escalations', type: 'plotPoint', multiple: true },
      { id: 'enhancedOutline', name: 'Enhanced Outline', type: 'outline' },
    ],
    parameters: [
      { id: 'intrigueType', name: 'Intrigue Focus', type: 'select', default: 'mystery', options: [
        { label: 'Mystery/Whodunit', value: 'mystery' },
        { label: 'Hidden Identities', value: 'identity' },
        { label: 'Conspiracy', value: 'conspiracy' },
        { label: 'Forbidden Secrets', value: 'forbidden' },
        { label: 'Romantic Tension', value: 'romantic' },
        { label: 'Survival Tension', value: 'survival' },
      ]},
      { id: 'intensity', name: 'Intrigue Intensity', type: 'slider', default: 0.6, min: 0, max: 1, step: 0.1 },
      { id: 'numSecrets', name: 'Number of Secrets', type: 'number', default: 3, min: 1, max: 10 },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'storyEnhancer',
    category: 'narrative',
    label: 'Story Enhancer',
    displayName: 'Enhance Story',
    description: 'Improve prose quality, pacing, emotional impact, or sensory detail.',
    quickHelp: 'Story content → Polished, enhanced version',
    useCase: 'Revision, improving drafts, adding depth',
    icon: 'AutoFixHigh',
    inputs: [
      { id: 'content', name: 'Content to Enhance', type: 'scene', required: true },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'enhancedContent', name: 'Enhanced Content', type: 'scene' },
      { id: 'suggestions', name: 'Further Suggestions', type: 'text', multiple: true },
    ],
    parameters: [
      { id: 'enhancementFocus', name: 'Enhancement Focus', type: 'select', default: 'comprehensive', options: [
        { label: 'Comprehensive Polish', value: 'comprehensive' },
        { label: 'Prose Quality', value: 'prose' },
        { label: 'Emotional Depth', value: 'emotional' },
        { label: "Sensory Detail (Show Don't Tell)", value: 'sensory' },
        { label: 'Pacing Improvement', value: 'pacing' },
        { label: 'Dialogue Naturalness', value: 'dialogue' },
        { label: 'Tension/Suspense', value: 'tension' },
      ]},
      { id: 'intensity', name: 'Enhancement Level', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
      { id: 'preserveVoice', name: 'Preserve Original Voice', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'storySynthesizer',
    category: 'output',
    label: 'Story Synthesizer',
    displayName: 'Export Story',
    description: 'Collect all story elements and export to various formats including JSON, Markdown, and PDF.',
    quickHelp: 'Story elements → Unified document for export or sharing',
    useCase: 'Exporting complete stories, creating story bibles, sharing with collaborators',
    icon: 'Article',
    inputs: [
      { id: 'story', name: 'Story Concept', type: 'story', required: true },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
      { id: 'outline', name: 'Story Outline', type: 'outline' },
      { id: 'scenes', name: 'Written Scenes', type: 'scene', multiple: true },
      { id: 'locations', name: 'Locations', type: 'location', multiple: true },
      { id: 'treatment', name: 'Treatment', type: 'treatment' },
    ],
    outputs: [
      { id: 'document', name: 'Story Document', type: 'text' },
      { id: 'exportUrl', name: 'Download URL', type: 'text' },
    ],
    parameters: [
      { id: 'format', name: 'Export Format', type: 'select', default: 'markdown', options: [
        { label: 'Markdown Document', value: 'markdown' },
        { label: 'JSON (Data)', value: 'json' },
        { label: 'Rich Text (RTF)', value: 'rtf' },
        { label: 'PDF Document', value: 'pdf' },
        { label: 'Fountain (Screenplay)', value: 'fountain' },
      ]},
      { id: 'sections', name: 'Include Sections', type: 'select', default: 'all', options: [
        { label: 'All Sections', value: 'all' },
        { label: 'Story & Characters Only', value: 'story-characters' },
        { label: 'Full Manuscript', value: 'manuscript' },
        { label: 'Story Bible', value: 'bible' },
        { label: 'Treatment Only', value: 'treatment' },
      ]},
      { id: 'includeMetadata', name: 'Include Metadata', type: 'boolean', default: true },
      { id: 'includeVisualPrompts', name: 'Include Visual Prompts', type: 'boolean', default: false },
    ],
    aiModel: 'gemini-2.5-flash',
  },

  // ============================================================================
  // CHARACTER DEVELOPMENT
  // ============================================================================
  {
    type: 'characterCreator',
    category: 'character',
    label: 'Character Creator',
    displayName: 'Create Character',
    description: 'Generate a complete character with personality, backstory, motivations, flaws, and arc.',
    quickHelp: 'Concept → Fully realized character with depth and complexity',
    useCase: 'Creating protagonists, antagonists, supporting cast',
    icon: 'PersonAdd',
    inputs: [
      { id: 'concept', name: 'Character Concept', type: 'text' },
      { id: 'characterSeed', name: 'Character Seed', type: 'character' },
      { id: 'story', name: 'Story Context', type: 'story' },
      { id: 'role', name: 'Story Role', type: 'text' },
    ],
    outputs: [
      { id: 'character', name: 'Character Profile', type: 'character' },
      { id: 'backstory', name: 'Backstory', type: 'text' },
      { id: 'arc', name: 'Character Arc', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'archetype', name: 'Base Archetype', type: 'select', default: 'none', options: [
        { label: 'None/Custom', value: 'none' },
        { label: 'The Hero', value: 'hero' },
        { label: 'The Mentor', value: 'mentor' },
        { label: 'The Threshold Guardian', value: 'guardian' },
        { label: 'The Herald', value: 'herald' },
        { label: 'The Shapeshifter', value: 'shapeshifter' },
        { label: 'The Shadow (Villain)', value: 'shadow' },
        { label: 'The Ally', value: 'ally' },
        { label: 'The Trickster', value: 'trickster' },
        { label: 'The Innocent', value: 'innocent' },
        { label: 'The Orphan', value: 'orphan' },
        { label: 'The Rebel', value: 'rebel' },
        { label: 'The Lover', value: 'lover' },
        { label: 'The Creator', value: 'creator' },
        { label: 'The Ruler', value: 'ruler' },
        { label: 'The Caregiver', value: 'caregiver' },
        { label: 'The Sage', value: 'sage' },
      ]},
      { id: 'depth', name: 'Character Depth', type: 'select', default: 'full', options: [
        { label: 'Sketch (Basic traits)', value: 'sketch' },
        { label: 'Standard (Personality + goals)', value: 'standard' },
        { label: 'Full (Complete psychology)', value: 'full' },
        { label: 'Deep Dive (Trauma, wounds, growth)', value: 'deep' },
      ]},
      { id: 'generateBackstory', name: 'Generate Backstory', type: 'boolean', default: true },
      { id: 'generateArc', name: 'Generate Character Arc', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'characterRelationship',
    category: 'character',
    label: 'Character Relationship',
    displayName: 'Define Relationship',
    description: 'Create and explore the relationship dynamics between two characters.',
    quickHelp: 'Two characters → Relationship history, dynamics, and conflicts',
    useCase: 'Building character chemistry, romantic subplots, rivalries',
    icon: 'People',
    inputs: [
      { id: 'character1', name: 'Character A', type: 'character', required: true },
      { id: 'character2', name: 'Character B', type: 'character', required: true },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'relationship', name: 'Relationship Profile', type: 'text' },
      { id: 'sharedHistory', name: 'Shared History', type: 'text' },
      { id: 'conflicts', name: 'Potential Conflicts', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'relationshipType', name: 'Relationship Type', type: 'select', default: 'allies', options: [
        { label: 'Romantic Partners', value: 'romantic' },
        { label: 'Friends/Allies', value: 'allies' },
        { label: 'Rivals/Enemies', value: 'rivals' },
        { label: 'Family', value: 'family' },
        { label: 'Mentor/Student', value: 'mentor' },
        { label: 'Colleagues', value: 'colleagues' },
        { label: 'Complicated/Ambiguous', value: 'complicated' },
      ]},
      { id: 'conflictLevel', name: 'Conflict Intensity', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
      { id: 'evolution', name: 'Relationship Evolution', type: 'select', default: 'static', options: [
        { label: 'Static (Unchanging)', value: 'static' },
        { label: 'Growing (Improving)', value: 'growing' },
        { label: 'Declining (Deteriorating)', value: 'declining' },
        { label: 'Transforming (Major shift)', value: 'transforming' },
        { label: 'Cyclical (On-again/off-again)', value: 'cyclical' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'characterVoice',
    category: 'dialogue',
    label: 'Character Voice',
    displayName: 'Define Voice',
    description: 'Establish a character\'s unique speaking style, vocabulary, and verbal quirks.',
    quickHelp: 'Character → Distinctive voice profile for consistent dialogue',
    useCase: 'Making each character sound unique and recognizable',
    icon: 'RecordVoiceOver',
    inputs: [
      { id: 'character', name: 'Character Profile', type: 'character', required: true },
    ],
    outputs: [
      { id: 'voiceProfile', name: 'Voice Profile', type: 'text' },
      { id: 'sampleDialogue', name: 'Sample Dialogue', type: 'dialogue' },
    ],
    parameters: [
      { id: 'speechPattern', name: 'Speech Pattern', type: 'select', default: 'standard', options: [
        { label: 'Standard/Neutral', value: 'standard' },
        { label: 'Formal/Educated', value: 'formal' },
        { label: 'Casual/Colloquial', value: 'casual' },
        { label: 'Street/Slang', value: 'street' },
        { label: 'Archaic/Period', value: 'archaic' },
        { label: 'Technical/Jargon', value: 'technical' },
        { label: 'Poetic/Flowery', value: 'poetic' },
        { label: 'Terse/Minimal', value: 'terse' },
      ]},
      { id: 'quirks', name: 'Add Verbal Quirks', type: 'boolean', default: true },
      { id: 'catchphrase', name: 'Generate Catchphrase', type: 'boolean', default: false },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'characterSheet',
    category: 'composite',
    label: 'Character Sheet',
    displayName: 'Create Character Sheet',
    description: 'Generate a visual character reference sheet with multiple views and expressions.',
    quickHelp: 'Character profile → Visual reference sheet',
    useCase: 'Character design, artist reference, consistency',
    icon: 'AssignmentInd',
    inputs: [
      { id: 'character', name: 'Character Profile', type: 'character', required: true },
      { id: 'style', name: 'Visual Style', type: 'style' },
    ],
    outputs: [
      { id: 'sheet', name: 'Character Sheet', type: 'image' },
      { id: 'expressions', name: 'Expression Grid', type: 'image' },
      { id: 'turnaround', name: 'Turnaround View', type: 'image' },
    ],
    parameters: [
      { id: 'sheetType', name: 'Sheet Type', type: 'select', default: 'comprehensive', options: [
        { label: 'Comprehensive (All views)', value: 'comprehensive' },
        { label: 'Portrait Focus', value: 'portrait' },
        { label: 'Full Body Turnaround', value: 'turnaround' },
        { label: 'Expression Sheet', value: 'expressions' },
        { label: 'Costume/Outfit Variations', value: 'costumes' },
      ]},
      { id: 'artStyle', name: 'Art Style', type: 'select', default: 'realistic', options: [
        { label: 'Realistic/Photographic', value: 'realistic' },
        { label: 'Stylized/Digital Art', value: 'stylized' },
        { label: 'Anime/Manga', value: 'anime' },
        { label: 'Western Animation', value: 'western' },
        { label: 'Comic Book', value: 'comic' },
      ]},
    ],
    aiModel: 'flux-2-pro',
  },

  // ============================================================================
  // WORLD BUILDING
  // ============================================================================
  {
    type: 'locationCreator',
    category: 'worldBuilding',
    label: 'Location Creator',
    displayName: 'Create Location',
    description: 'Generate a detailed location with atmosphere, history, and narrative potential.',
    quickHelp: 'Concept → Vivid setting with sensory details and story hooks',
    useCase: 'Creating memorable settings, establishing mood',
    icon: 'Place',
    inputs: [
      { id: 'concept', name: 'Location Concept', type: 'text' },
      { id: 'locationSeed', name: 'Location Seed', type: 'location' },
      { id: 'story', name: 'Story Context', type: 'story' },
      { id: 'lore', name: 'World Lore', type: 'lore' },
    ],
    outputs: [
      { id: 'location', name: 'Location Profile', type: 'location' },
      { id: 'description', name: 'Rich Description', type: 'text' },
      { id: 'secrets', name: 'Hidden Elements', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'locationType', name: 'Location Type', type: 'select', default: 'interior', options: [
        { label: 'Interior Space', value: 'interior' },
        { label: 'Exterior/Landscape', value: 'exterior' },
        { label: 'Urban Environment', value: 'urban' },
        { label: 'Rural/Natural', value: 'rural' },
        { label: 'Fantastical/Other-worldly', value: 'fantastical' },
        { label: 'Historical/Period', value: 'historical' },
        { label: 'Futuristic/Sci-Fi', value: 'futuristic' },
      ]},
      { id: 'mood', name: 'Atmospheric Mood', type: 'select', default: 'neutral', options: [
        { label: 'Neutral', value: 'neutral' },
        { label: 'Warm/Inviting', value: 'warm' },
        { label: 'Cold/Hostile', value: 'cold' },
        { label: 'Mysterious/Eerie', value: 'mysterious' },
        { label: 'Chaotic/Dangerous', value: 'chaotic' },
        { label: 'Serene/Peaceful', value: 'serene' },
        { label: 'Oppressive/Trapped', value: 'oppressive' },
      ]},
      { id: 'sensoryDetail', name: 'Sensory Detail Level', type: 'slider', default: 0.7, min: 0, max: 1, step: 0.1 },
      { id: 'includeHistory', name: 'Include History', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'worldLore',
    category: 'worldBuilding',
    label: 'World Lore',
    displayName: 'Create Lore',
    description: 'Generate mythology, history, rules, and background lore for your story world.',
    quickHelp: 'Theme + Setting → Rich world history and mythology',
    useCase: 'Fantasy/sci-fi world-building, establishing rules and history',
    icon: 'MenuBook',
    inputs: [
      { id: 'worldConcept', name: 'World Concept', type: 'text', required: true },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'lore', name: 'World Lore', type: 'lore' },
      { id: 'history', name: 'Historical Timeline', type: 'timeline' },
      { id: 'factions', name: 'Factions/Groups', type: 'text', multiple: true },
    ],
    parameters: [
      { id: 'loreType', name: 'Lore Focus', type: 'select', default: 'comprehensive', options: [
        { label: 'Comprehensive (All aspects)', value: 'comprehensive' },
        { label: 'Historical (Events & eras)', value: 'historical' },
        { label: 'Mythological (Gods & legends)', value: 'mythological' },
        { label: 'Political (Factions & power)', value: 'political' },
        { label: 'Magical/Tech System', value: 'systems' },
        { label: 'Cultural (Customs & beliefs)', value: 'cultural' },
      ]},
      { id: 'depth', name: 'Lore Depth', type: 'select', default: 'standard', options: [
        { label: 'Surface (Key facts only)', value: 'surface' },
        { label: 'Standard (Main elements)', value: 'standard' },
        { label: 'Deep (Detailed history)', value: 'deep' },
        { label: 'Encyclopedic (Everything)', value: 'encyclopedic' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'storyTimeline',
    category: 'worldBuilding',
    label: 'Timeline',
    displayName: 'Create Timeline',
    description: 'Generate a chronological timeline of events for your story or world history.',
    quickHelp: 'Story/Lore → Organized chronological events',
    useCase: 'Tracking story events, historical backstory, parallel plotlines',
    icon: 'Timeline',
    inputs: [
      { id: 'story', name: 'Story', type: 'story' },
      { id: 'lore', name: 'World Lore', type: 'lore' },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
    ],
    outputs: [
      { id: 'timeline', name: 'Event Timeline', type: 'timeline' },
      { id: 'events', name: 'Key Events', type: 'plotPoint', multiple: true },
    ],
    parameters: [
      { id: 'scope', name: 'Timeline Scope', type: 'select', default: 'story', options: [
        { label: 'Story Events Only', value: 'story' },
        { label: 'Character Lifetimes', value: 'characters' },
        { label: 'World History', value: 'world' },
        { label: 'Comprehensive (All)', value: 'comprehensive' },
      ]},
      { id: 'granularity', name: 'Event Granularity', type: 'select', default: 'scenes', options: [
        { label: 'Major Events Only', value: 'major' },
        { label: 'Scene-Level', value: 'scenes' },
        { label: 'Detailed (Hour by hour)', value: 'detailed' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },

  // ============================================================================
  // DIALOGUE
  // ============================================================================
  {
    type: 'dialogueGenerator',
    category: 'dialogue',
    label: 'Dialogue Generator',
    displayName: 'Write Dialogue',
    description: 'Generate authentic dialogue between characters with subtext and conflict.',
    quickHelp: 'Characters + Situation → Natural, character-driven dialogue',
    useCase: 'Writing conversations, confrontations, romantic scenes',
    icon: 'Chat',
    inputs: [
      { id: 'characters', name: 'Characters Speaking', type: 'character', multiple: true, required: true },
      { id: 'situation', name: 'Situation/Context', type: 'text' },
      { id: 'scene', name: 'Scene Context', type: 'scene' },
      { id: 'story', name: 'Story Context', type: 'story' },
      { id: 'location', name: 'Location', type: 'location' },
      { id: 'precedingDialogue', name: 'Previous Dialogue', type: 'dialogue' },
    ],
    outputs: [
      { id: 'dialogue', name: 'Dialogue Exchange', type: 'dialogue' },
      { id: 'subtext', name: 'Subtext Analysis', type: 'text' },
    ],
    parameters: [
      { id: 'dialogueType', name: 'Dialogue Type', type: 'select', default: 'dramatic', options: [
        { label: 'Casual Conversation', value: 'casual' },
        { label: 'Dramatic/Tense', value: 'dramatic' },
        { label: 'Romantic', value: 'romantic' },
        { label: 'Comedic/Banter', value: 'comedic' },
        { label: 'Expository', value: 'expository' },
        { label: 'Confrontational', value: 'confrontational' },
        { label: 'Interrogation', value: 'interrogation' },
      ]},
      { id: 'subtextLevel', name: 'Subtext Complexity', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
      { id: 'length', name: 'Exchange Length', type: 'select', default: 'medium', options: [
        { label: 'Brief (5-10 lines)', value: 'brief' },
        { label: 'Medium (10-25 lines)', value: 'medium' },
        { label: 'Extended (25-50 lines)', value: 'extended' },
      ]},
      { id: 'format', name: 'Output Format', type: 'select', default: 'prose', options: [
        { label: 'Prose (with tags)', value: 'prose' },
        { label: 'Screenplay Format', value: 'screenplay' },
        { label: 'Play Format', value: 'play' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'monologueGenerator',
    category: 'dialogue',
    label: 'Monologue Generator',
    displayName: 'Write Monologue',
    description: 'Generate a powerful monologue or speech for a character.',
    quickHelp: 'Character + Theme → Compelling speech or inner monologue',
    useCase: 'Key character speeches, villain revelations, climactic moments',
    icon: 'Mic',
    inputs: [
      { id: 'character', name: 'Speaking Character', type: 'character', required: true },
      { id: 'theme', name: 'Theme/Topic', type: 'text', required: true },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'monologue', name: 'Monologue', type: 'dialogue' },
    ],
    parameters: [
      { id: 'monologueType', name: 'Monologue Type', type: 'select', default: 'dramatic', options: [
        { label: 'Internal/Stream of Consciousness', value: 'internal' },
        { label: 'Dramatic Speech', value: 'dramatic' },
        { label: 'Villain Reveal', value: 'villain' },
        { label: 'Inspirational', value: 'inspirational' },
        { label: 'Confession', value: 'confession' },
        { label: 'Eulogy/Memorial', value: 'eulogy' },
        { label: 'Declaration of Love', value: 'love' },
        { label: 'Philosophical', value: 'philosophical' },
      ]},
      { id: 'length', name: 'Length', type: 'select', default: 'medium', options: [
        { label: 'Short (30-60 seconds)', value: 'short' },
        { label: 'Medium (1-2 minutes)', value: 'medium' },
        { label: 'Extended (2-5 minutes)', value: 'extended' },
      ]},
      { id: 'emotionalIntensity', name: 'Emotional Intensity', type: 'slider', default: 0.7, min: 0, max: 1, step: 0.1 },
    ],
    aiModel: 'gemini-2.5-flash',
  },

  // ============================================================================
  // BRANCHING NARRATIVES
  // ============================================================================
  {
    type: 'choicePoint',
    category: 'branching',
    label: 'Choice Point',
    displayName: 'Create Choice',
    description: 'Create a branching decision point where the story can diverge.',
    quickHelp: 'Story moment → Multiple possible paths with consequences',
    useCase: 'Interactive fiction, games, choose-your-own-adventure',
    icon: 'CallSplit',
    inputs: [
      { id: 'precedingScene', name: 'Preceding Scene', type: 'scene', required: true },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'choice', name: 'Choice Point', type: 'plotPoint' },
      { id: 'optionA', name: 'Option A Path', type: 'scene' },
      { id: 'optionB', name: 'Option B Path', type: 'scene' },
      { id: 'optionC', name: 'Option C Path', type: 'scene' },
    ],
    parameters: [
      { id: 'numChoices', name: 'Number of Choices', type: 'select', default: '2', options: [
        { label: 'Binary (2 choices)', value: '2' },
        { label: 'Triple (3 choices)', value: '3' },
        { label: 'Multiple (4 choices)', value: '4' },
      ]},
      { id: 'choiceType', name: 'Choice Nature', type: 'select', default: 'moral', options: [
        { label: 'Moral Dilemma', value: 'moral' },
        { label: 'Action Choice', value: 'action' },
        { label: 'Dialogue Response', value: 'dialogue' },
        { label: 'Strategic Decision', value: 'strategic' },
        { label: 'Relationship Choice', value: 'relationship' },
      ]},
      { id: 'consequenceWeight', name: 'Consequence Impact', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
      { id: 'convergence', name: 'Path Convergence', type: 'select', default: 'delayed', options: [
        { label: 'Immediate (Next scene)', value: 'immediate' },
        { label: 'Delayed (Few scenes)', value: 'delayed' },
        { label: 'Major Branch (Long divergence)', value: 'major' },
        { label: 'Permanent (Different endings)', value: 'permanent' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'consequenceTracker',
    category: 'branching',
    label: 'Consequence Tracker',
    displayName: 'Track Consequences',
    description: 'Track accumulated choices and determine their long-term story impacts.',
    quickHelp: 'Choice history → Meaningful consequences and variations',
    useCase: 'Managing branching complexity, ensuring choices matter',
    icon: 'AccountBalance',
    inputs: [
      { id: 'choices', name: 'Previous Choices', type: 'plotPoint', multiple: true, required: true },
      { id: 'story', name: 'Story Context', type: 'story' },
      { id: 'characters', name: 'Characters', type: 'character', multiple: true },
    ],
    outputs: [
      { id: 'consequences', name: 'Accumulated Consequences', type: 'plotPoint', multiple: true },
      { id: 'characterChanges', name: 'Character State Changes', type: 'character', multiple: true },
      { id: 'worldChanges', name: 'World State Changes', type: 'lore' },
    ],
    parameters: [
      { id: 'evaluationType', name: 'Evaluation Type', type: 'select', default: 'narrative', options: [
        { label: 'Narrative (Story impact)', value: 'narrative' },
        { label: 'Character (Relationship changes)', value: 'character' },
        { label: 'World (Setting changes)', value: 'world' },
        { label: 'Comprehensive (All)', value: 'comprehensive' },
      ]},
    ],
    aiModel: 'gemini-2.5-flash',
  },
  {
    type: 'pathMerge',
    category: 'branching',
    label: 'Path Merge',
    displayName: 'Merge Paths',
    description: 'Reunite divergent story branches while honoring previous choices.',
    quickHelp: 'Multiple paths → Single continuation that acknowledges all',
    useCase: 'Managing branching complexity, creating convergence points',
    icon: 'CallMerge',
    inputs: [
      { id: 'pathA', name: 'Path A', type: 'scene', required: true },
      { id: 'pathB', name: 'Path B', type: 'scene', required: true },
      { id: 'pathC', name: 'Path C (Optional)', type: 'scene' },
      { id: 'story', name: 'Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'mergedScene', name: 'Merged Scene', type: 'scene' },
      { id: 'variationNotes', name: 'Path-Specific Variations', type: 'text', multiple: true },
    ],
    parameters: [
      { id: 'mergeStyle', name: 'Merge Style', type: 'select', default: 'variations', options: [
        { label: 'Single Scene + Variations', value: 'variations' },
        { label: 'Common Ground Only', value: 'common' },
        { label: 'Acknowledge All Paths', value: 'acknowledge' },
      ]},
      { id: 'retainMemory', name: 'Retain Choice Memory', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },

  // ============================================================================
  // VISUALIZATION & OUTPUT
  // ============================================================================
  {
    type: 'sceneVisualizer',
    category: 'composite',
    label: 'Scene Visualizer',
    displayName: 'Visualize Scene',
    description: 'Generate storyboard frames or concept art from scene descriptions.',
    quickHelp: 'Scene → Visual representations with character consistency',
    useCase: 'Storyboarding, visualization, pitch materials',
    icon: 'Panorama',
    inputs: [
      { id: 'scene', name: 'Scene', type: 'scene', required: true },
      { id: 'characters', name: 'Character References', type: 'character', multiple: true },
      { id: 'location', name: 'Location Reference', type: 'location' },
      { id: 'style', name: 'Visual Style', type: 'style' },
    ],
    outputs: [
      { id: 'frames', name: 'Storyboard Frames', type: 'image', multiple: true },
      { id: 'keyFrame', name: 'Key Frame', type: 'image' },
    ],
    parameters: [
      { id: 'numFrames', name: 'Number of Frames', type: 'slider', default: 3, min: 1, max: 9, step: 1 },
      { id: 'visualStyle', name: 'Visual Style', type: 'select', default: 'cinematic', options: [
        { label: 'Cinematic/Photorealistic', value: 'cinematic' },
        { label: 'Illustrated/Storyboard', value: 'illustrated' },
        { label: 'Comic Book', value: 'comic' },
        { label: 'Concept Art', value: 'concept' },
        { label: 'Animated/Pixar Style', value: 'animated' },
        { label: 'Manga/Anime', value: 'manga' },
      ]},
      { id: 'aspectRatio', name: 'Frame Aspect Ratio', type: 'select', default: '16:9', options: [
        { label: '16:9 (Widescreen)', value: '16:9' },
        { label: '2.35:1 (Cinematic)', value: '2.35:1' },
        { label: '1:1 (Square)', value: '1:1' },
        { label: '9:16 (Vertical)', value: '9:16' },
      ]},
      { id: 'characterConsistency', name: 'Character Consistency', type: 'boolean', default: true },
    ],
    aiModel: 'flux-2-pro',
  },
  {
    type: 'screenplayFormatter',
    category: 'output',
    label: 'Screenplay Formatter',
    displayName: 'Format as Screenplay',
    description: 'Convert story content into proper industry-standard screenplay format.',
    quickHelp: 'Scene/Story → Formatted screenplay pages',
    useCase: 'Creating scripts, professional formatting',
    icon: 'LocalMovies',
    inputs: [
      { id: 'content', name: 'Story Content', type: 'scene', required: true },
      { id: 'story', name: 'Full Story Context', type: 'story' },
    ],
    outputs: [
      { id: 'screenplay', name: 'Formatted Screenplay', type: 'text' },
      { id: 'pageCount', name: 'Estimated Page Count', type: 'text' },
    ],
    parameters: [
      { id: 'format', name: 'Script Format', type: 'select', default: 'film', options: [
        { label: 'Feature Film', value: 'film' },
        { label: 'TV Episode (Hour)', value: 'tv-hour' },
        { label: 'TV Episode (Half-hour)', value: 'tv-half' },
        { label: 'Short Film', value: 'short' },
        { label: 'Web Series', value: 'web' },
      ]},
      { id: 'includeSluglines', name: 'Include Scene Headers', type: 'boolean', default: true },
      { id: 'includeParentheticals', name: 'Include Parentheticals', type: 'boolean', default: true },
    ],
    aiModel: 'gemini-2.5-flash',
  },
];
