/**
 * Video Generation Nodes - AI video, 3D, and character consistency models
 */
import type { NodeDefinition } from '@/models/canvas';

export const videoGenNodes: NodeDefinition[] = [
  // VIDEO GENERATION
  {
    type: 'kling26T2V',
    category: 'videoGen',
    label: 'Kling 2.6 T2V',
    displayName: 'Text to Video',
    description: 'Create videos directly from text descriptions. Includes optional AI-generated sound.',
    quickHelp: 'Describe a scene → Watch it come to life',
    useCase: 'Social media clips, concept videos, story sequences',
    icon: 'Videocam',
    aiModel: 'kling',
    tier: 'production',
    hasAudio: true,
    inputs: [
      { id: 'prompt', name: 'Scene Description (Text Input)', type: 'text', required: true },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'duration', name: 'Duration (s)', type: 'select', default: 5, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
      ]},
      { id: 'aspectRatio', name: 'Aspect Ratio', type: 'select', default: '16:9', options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
      ]},
      { id: 'enableAudio', name: 'Generate Audio', type: 'boolean', default: true },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'aspectRatio'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
  {
    type: 'kling26I2V',
    category: 'videoGen',
    label: 'Kling 2.6 I2V',
    displayName: 'Animate Image',
    description: 'Bring any still image to life with natural motion and animation.',
    quickHelp: 'Static image → Animated video',
    useCase: 'Fashion runway videos, product animations, photo animations',
    icon: 'Animation',
    aiModel: 'kling',
    tier: 'production',
    inputs: [
      { id: 'image', name: 'Source Image (Image Upload)', type: 'image', required: true },
      { id: 'prompt', name: 'Motion Prompt (Text Input)', type: 'text' },
    ],
    outputs: [{ id: 'video', name: 'Video', type: 'video' }],
    parameters: [
      { id: 'duration', name: 'Duration (s)', type: 'select', default: 5, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
      ]},
      { id: 'motionIntensity', name: 'Motion Intensity', type: 'slider', default: 0.5, min: 0, max: 1, step: 0.1 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'motionIntensity'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
  {
    type: 'klingO1Ref2V',
    category: 'videoGen',
    label: 'Kling O1 Ref2V',
    displayName: 'Character Video',
    description: 'Create videos starring specific characters/people from reference photos. Maintains identity.',
    quickHelp: 'Person photos + Scene → Video with that person',
    useCase: 'Personalized content, character-driven stories, product demos',
    icon: 'PersonVideo',
    aiModel: 'kling',
    tier: 'production',
    bestFor: 'faces',
    inputs: [
      { id: 'references', name: 'Person Photos (Image Upload)', type: 'image', multiple: true, required: true },
      { id: 'prompt', name: 'Scene Description (Text Input)', type: 'text', required: true },
    ],
    outputs: [{ id: 'video', name: 'Video', type: 'video' }],
    parameters: [
      { id: 'duration', name: 'Duration (s)', type: 'select', default: 5, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
      ]},
      { id: 'characterWeight', name: 'Character Weight', type: 'slider', default: 0.8, min: 0, max: 1, step: 0.1 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'characterWeight'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
  {
    type: 'veo31',
    category: 'videoGen',
    label: 'VEO 3.1',
    displayName: 'Cinematic Video',
    description: 'Google\'s premium video generator. Creates cinematic, film-quality videos with natural audio.',
    quickHelp: 'Prompt → Hollywood-quality video clip',
    useCase: 'Film teasers, high-end ads, cinematic storytelling',
    icon: 'Movie',
    aiModel: 'veo',
    tier: 'flagship',
    hasAudio: true,
    inputs: [
      { id: 'prompt', name: 'Scene Description (Text Input)', type: 'text', required: true },
      { id: 'image', name: 'First Frame (Image Upload)', type: 'image' },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'aspectRatio', name: 'Aspect Ratio', type: 'select', default: '16:9', options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
      ]},
      { id: 'mode', name: 'Mode', type: 'select', default: 'fast', options: [
        { label: 'Fast ($0.15/s)', value: 'fast' },
        { label: 'Standard ($0.40/s)', value: 'standard' },
      ]},
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['aspectRatio', 'mode'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true, showCost: true },
    },
  },
  {
    type: 'klingAvatar',
    category: 'videoGen',
    label: 'Kling Avatar',
    displayName: 'Talking Head Video',
    description: 'Create a video of a face speaking with perfect lip sync. Upload a photo and audio to bring it to life.',
    quickHelp: 'Face photo + Audio → Talking video',
    useCase: 'Social media content, presentations, virtual spokespersons',
    icon: 'RecordVoiceOver',
    aiModel: 'kling',
    tier: 'production',
    bestFor: 'faces',
    inputs: [
      { id: 'image', name: 'Portrait', type: 'image', required: true },
      { id: 'audio', name: 'Audio', type: 'audio', required: true },
    ],
    outputs: [{ id: 'video', name: 'Video', type: 'video' }],
    parameters: [
      { id: 'lipSyncStrength', name: 'Lip Sync Strength', type: 'slider', default: 0.8, min: 0, max: 1, step: 0.1 },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '1:1', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['lipSyncStrength'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
  // === NEW DECEMBER 2025 VIDEO MODELS ===
  {
    type: 'sora2',
    category: 'videoGen',
    label: 'Sora 2',
    displayName: 'Sora Video Generator',
    description: 'OpenAI\'s state-of-the-art video model with realistic physics, native audio, and multi-shot capabilities. Includes the Cameos feature.',
    quickHelp: 'Best physics & realism with synchronized audio',
    useCase: 'Professional video content, cinematic scenes, realistic motion',
    icon: 'AutoAwesome',
    aiModel: 'sora',
    tier: 'flagship',
    hasAudio: true,
    cost: '$0.50/sec',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
      { id: 'image', name: 'First Frame (optional)', type: 'image' },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'duration', name: 'Duration', type: 'select', default: 5, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
        { label: '15 seconds', value: 15 },
      ]},
      { id: 'aspectRatio', name: 'Aspect Ratio', type: 'select', default: '16:9', options: [
        { label: '16:9 (Landscape)', value: '16:9' },
        { label: '9:16 (Portrait)', value: '9:16' },
        { label: '1:1 (Square)', value: '1:1' },
      ]},
      { id: 'enableAudio', name: 'Generate Audio', type: 'boolean', default: true },
      { id: 'audioPrompt', name: 'Audio Direction', type: 'text', default: '' },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'aspectRatio'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true, showCost: true },
    },
  },
  {
    type: 'sora2Pro',
    category: 'videoGen',
    label: 'Sora 2 Pro',
    displayName: 'Sora Pro Video',
    description: 'OpenAI\'s flagship video model. Best physics, realism, and multi-shot coherence. Premium quality output.',
    quickHelp: 'Premium tier with best quality and control',
    useCase: 'Commercial productions, film-quality content, premium ads',
    icon: 'WorkspacePremium',
    aiModel: 'sora',
    tier: 'flagship',
    hasAudio: true,
    cost: '$0.80/sec',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
      { id: 'image', name: 'First Frame', type: 'image' },
      { id: 'storyboard', name: 'Multi-shot Storyboard', type: 'image', multiple: true },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'duration', name: 'Duration', type: 'select', default: 10, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
        { label: '15 seconds', value: 15 },
        { label: '20 seconds', value: 20 },
      ]},
      { id: 'aspectRatio', name: 'Aspect Ratio', type: 'select', default: '16:9', options: [
        { label: '16:9 (Cinematic)', value: '16:9' },
        { label: '21:9 (Ultra-wide)', value: '21:9' },
        { label: '9:16 (Portrait)', value: '9:16' },
        { label: '1:1 (Square)', value: '1:1' },
      ]},
      { id: 'enableAudio', name: 'Generate Audio', type: 'boolean', default: true },
      { id: 'audioPrompt', name: 'Audio Direction', type: 'text', default: '' },
      { id: 'multiShot', name: 'Multi-shot Mode', type: 'boolean', default: false },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'stack', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'aspectRatio', 'multiShot'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true, showCost: true },
    },
  },
  {
    type: 'kling26Pro',
    category: 'videoGen',
    label: 'Kling 2.6 Pro',
    displayName: 'Kling Pro Video',
    description: 'Top-tier cinematic video with native bilingual audio (EN/ZH). Supports extended generation up to 3 minutes.',
    quickHelp: 'Cinematic quality with voice and sound',
    useCase: 'Long-form content, dialogue scenes, cinematic storytelling',
    icon: 'TheaterComedy',
    aiModel: 'kling',
    tier: 'flagship',
    hasAudio: true,
    cost: '$0.14/sec',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
      { id: 'image', name: 'First Frame', type: 'image' },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'duration', name: 'Duration', type: 'select', default: 10, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
        { label: '30 seconds', value: 30 },
        { label: '60 seconds', value: 60 },
        { label: '180 seconds (3 min)', value: 180 },
      ]},
      { id: 'aspectRatio', name: 'Aspect Ratio', type: 'select', default: '16:9', options: [
        { label: '16:9', value: '16:9' },
        { label: '9:16', value: '9:16' },
        { label: '1:1', value: '1:1' },
      ]},
      { id: 'enableAudio', name: 'Generate Audio', type: 'boolean', default: true },
      { id: 'audioLanguage', name: 'Audio Language', type: 'select', default: 'en', options: [
        { label: 'English', value: 'en' },
        { label: 'Chinese', value: 'zh' },
        { label: 'Auto-detect', value: 'auto' },
      ]},
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'stack', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'aspectRatio', 'audioLanguage'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true, showCost: true },
    },
  },
  {
    type: 'ltx2',
    category: 'videoGen',
    label: 'LTX-2',
    displayName: '4K Video Generator',
    description: 'Open-source 4K video at 50fps with synchronized audio. Excellent value for high-fidelity output.',
    quickHelp: '4K resolution with audio at competitive cost',
    useCase: 'High-resolution content, smooth motion, professional quality',
    icon: 'Hd',
    aiModel: 'luma',
    tier: 'production',
    hasAudio: true,
    cost: '$0.16/sec',
    inputs: [
      { id: 'prompt', name: 'Prompt', type: 'text', required: true },
      { id: 'image', name: 'First Frame', type: 'image' },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'duration', name: 'Duration', type: 'select', default: 6, options: [
        { label: '6 seconds', value: 6 },
        { label: '8 seconds', value: 8 },
        { label: '10 seconds', value: 10 },
      ]},
      { id: 'resolution', name: 'Resolution', type: 'select', default: '1080p', options: [
        { label: '1080p HD', value: '1080p' },
        { label: '4K Ultra HD', value: '4k' },
      ]},
      { id: 'fps', name: 'Frame Rate', type: 'select', default: 30, options: [
        { label: '30 fps', value: 30 },
        { label: '50 fps', value: 50 },
      ]},
      { id: 'enableAudio', name: 'Generate Audio', type: 'boolean', default: true },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['duration', 'resolution', 'fps'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true, showCost: true },
    },
  },
  {
    type: 'wan26',
    category: 'videoGen',
    label: 'WAN 2.6',
    displayName: 'Multi-Shot Video',
    description: 'Create multi-shot videos with scene transitions and audio. Ideal for narrative content up to 15 seconds.',
    quickHelp: 'Multiple shots with transitions in one video',
    useCase: 'Story sequences, trailers, multi-scene content',
    icon: 'ViewCarousel',
    aiModel: 'minimax',
    tier: 'creative',
    hasAudio: true,
    inputs: [
      { id: 'prompt', name: 'Scene Descriptions', type: 'text', required: true },
      { id: 'images', name: 'Scene References', type: 'image', multiple: true },
    ],
    outputs: [
      { id: 'video', name: 'Video', type: 'video' },
      { id: 'audio', name: 'Audio', type: 'audio' },
    ],
    parameters: [
      { id: 'numShots', name: 'Number of Shots', type: 'number', default: 3, min: 2, max: 6 },
      { id: 'duration', name: 'Total Duration', type: 'select', default: 10, options: [
        { label: '10 seconds', value: 10 },
        { label: '15 seconds', value: 15 },
      ]},
      { id: 'transitionStyle', name: 'Transition Style', type: 'select', default: 'cut', options: [
        { label: 'Cut', value: 'cut' },
        { label: 'Fade', value: 'fade' },
        { label: 'Dissolve', value: 'dissolve' },
      ]},
      { id: 'enableAudio', name: 'Generate Audio', type: 'boolean', default: true },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'video', aspectRatio: '16:9', showFullscreen: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['numShots', 'duration', 'transitionStyle'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },

  // 3D GENERATION NODES
  {
    type: 'meshy6',
    category: 'threeD',
    label: 'Meshy 6',
    displayName: '3D Model from Image',
    description: 'Convert any image into a full 3D model with realistic textures and materials.',
    quickHelp: 'Product photo → Rotatable 3D model',
    useCase: 'E-commerce 3D views, game assets, product visualization',
    icon: 'ViewInAr',
    aiModel: 'meshy',
    inputs: [
      { id: 'image', name: 'Source Image', type: 'image', required: true },
    ],
    outputs: [{ id: 'mesh', name: '3D Mesh', type: 'mesh3d' }],
    parameters: [
      { id: 'targetPolycount', name: 'Polycount', type: 'select', default: 'medium', options: [
        { label: 'Low (10K)', value: 'low' },
        { label: 'Medium (30K)', value: 'medium' },
        { label: 'High (100K)', value: 'high' },
      ]},
      { id: 'generatePBR', name: 'Generate PBR', type: 'boolean', default: true },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: '3d', aspectRatio: '1:1', showZoom: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['targetPolycount', 'generatePBR'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
  {
    type: 'tripoV25',
    category: 'threeD',
    label: 'Tripo v2.5',
    displayName: '3D Model (Fast)',
    description: 'Quickly generate 3D models optimized for animation and game engines.',
    quickHelp: 'Image → Game-ready 3D asset',
    useCase: 'Game development, AR/VR assets, rapid prototyping',
    icon: '3dRotation',
    aiModel: 'tripo',
    inputs: [
      { id: 'image', name: 'Source Image', type: 'image', required: true },
    ],
    outputs: [{ id: 'mesh', name: '3D Mesh', type: 'mesh3d' }],
    parameters: [
      { id: 'format', name: 'Export Format', type: 'select', default: 'glb', options: [
        { label: 'GLB', value: 'glb' },
        { label: 'FBX', value: 'fbx' },
        { label: 'OBJ', value: 'obj' },
      ]},
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: '3d', aspectRatio: '1:1', showZoom: true },
      parameters: { layout: 'inline', visibleInModes: ['standard', 'expanded'], priorityParams: ['format'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },

  // CHARACTER CONSISTENCY NODES
  {
    type: 'characterLock',
    category: 'character',
    label: 'Character Lock',
    displayName: 'Character Identity Lock',
    description: 'Lock a character\'s appearance so they stay consistent across all your scenes. Upload reference images to create an identity.',
    quickHelp: 'Reference images → Consistent character in every scene',
    useCase: 'Children\'s books, comics, storytelling with recurring characters',
    icon: 'Lock',
    inputs: [
      { id: 'references', name: 'Reference Images', type: 'image', multiple: true, required: true },
    ],
    outputs: [{ id: 'character', name: 'Character Profile', type: 'character' }],
    parameters: [
      { id: 'characterName', name: 'Character Name', type: 'text', default: '' },
      { id: 'preserveStrength', name: 'Identity Preservation', type: 'slider', default: 0.8, min: 0, max: 1, step: 0.05 },
      { id: 'extractTraits', name: 'Auto-Extract Traits', type: 'boolean', default: true },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'gallery', aspectRatio: '3:4', showZoom: true },
      parameters: { layout: 'stack', visibleInModes: ['standard', 'expanded'], priorityParams: ['characterName', 'preserveStrength'] },
      actions: { primary: 'execute', showProgress: true },
    },
  },
  {
    type: 'faceMemory',
    category: 'character',
    label: 'Face Memory',
    displayName: 'Face Library',
    description: 'Store up to 5 different faces for use in multi-character scenes.',
    quickHelp: 'Upload faces → Use them in any generation',
    useCase: 'Family photos, team shots, group storytelling',
    icon: 'Face',
    inputs: [
      { id: 'faces', name: 'Face Images', type: 'image', multiple: true, required: true },
    ],
    outputs: [{ id: 'memory', name: 'Face Memory', type: 'character' }],
    parameters: [
      { id: 'slot1Name', name: 'Face 1 Name', type: 'text', default: 'Face 1' },
      { id: 'slot2Name', name: 'Face 2 Name', type: 'text', default: 'Face 2' },
      { id: 'slot3Name', name: 'Face 3 Name', type: 'text', default: 'Face 3' },
      { id: 'slot4Name', name: 'Face 4 Name', type: 'text', default: 'Face 4' },
      { id: 'slot5Name', name: 'Face 5 Name', type: 'text', default: 'Face 5' },
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'gallery', aspectRatio: '1:1', showZoom: true },
      parameters: { layout: 'stack', visibleInModes: ['standard', 'expanded'], priorityParams: ['slot1Name', 'slot2Name', 'slot3Name'] },
      actions: { primary: 'execute', showProgress: true },
    },
  },
  {
    type: 'elementLibrary',
    category: 'character',
    label: 'Element Library',
    displayName: 'Asset Library',
    description: 'Save reusable elements (characters, objects, environments) for consistent video generation.',
    quickHelp: 'Save assets → Reuse across videos',
    useCase: 'Brand characters, product consistency, story continuity',
    icon: 'LibraryBooks',
    aiModel: 'kling',
    inputs: [
      { id: 'elements', name: 'Element Images', type: 'image', multiple: true },
    ],
    outputs: [
      { id: 'library', name: 'Element Library', type: 'character' },
      { id: 'video', name: 'Video Output', type: 'video' },
    ],
    parameters: [
      { id: 'libraryName', name: 'Library Name', type: 'text', default: '' },
      { id: 'elementType', name: 'Element Type', type: 'select', default: 'character', options: [
        { label: 'Character', value: 'character' },
        { label: 'Object', value: 'object' },
        { label: 'Environment', value: 'environment' },
      ]},
      { id: 'duration', name: 'Video Duration', type: 'select', default: 5, options: [
        { label: '5 seconds', value: 5 },
        { label: '10 seconds', value: 10 },
      ]},
    ],
    defaultDisplayMode: 'standard',
    slots: {
      preview: { type: 'gallery', aspectRatio: 'auto', showZoom: true },
      parameters: { layout: 'stack', visibleInModes: ['standard', 'expanded'], priorityParams: ['libraryName', 'elementType', 'duration'] },
      actions: { primary: 'execute', secondary: ['download'], showProgress: true },
    },
  },
];
